application: gdaysuganda
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /fonts
  static_dir: fonts


- url: /images
  static_dir: images
  
- url: /(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))

- url: /admin/.*
  script: admin.php
  login: admin

- url: /.*
  script: not_found.php